// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"
)

const TableNameBaisc = "baisc"

// Baisc mapped from table <baisc>
type Baisc struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`                                             // 主键
	CreatedTime time.Time `gorm:"column:created_time;not null;default:CURRENT_TIMESTAMP" json:"created_time"` // 创建时间
	UpdatedTime time.Time `gorm:"column:updated_time;not null;default:CURRENT_TIMESTAMP" json:"updated_time"` // 更新时间
}

// TableName Baisc's table name
func (*Baisc) TableName() string {
	return TableNameBaisc
}
